### ISSUE TITLE
Script for Registration of Schemas

### ISSUE THREAD

**Issue by wilwade** [LibertyDSNP/schemas#3]
As a user, I want to be able to register the schemas to a Frequency instance, so that I can then use those schemas.

## Acceptance Criteria
- [x] npm script that I can call that registers all the schemas (or a specific one)
- [x] Should remove whitespace for smaller schema
- [x] Some way to configure, env var, or parameter the instance and key
    - [x] Be nice if there was a way to default to the Substrate Alice key and localhost

## Arch Notes
- There is an example Schema registration in an example-client-frequency branch
- https://libertydsnp.github.io/frequency/pallet_schemas/index.html
- https://github.com/LibertyDSNP/frequency/tree/main/js/api-augment

**Comment by rlaferla** [comment]
It appears that the register_schema method is not in the augment-api-rpc interface.  Is this intentional?  Does it need to be added? (edited)

**Comment by rlaferla** [comment]
**Pre-work:** 

- [ ] Fix `Type 'null' is not assignable to type 'BloomFilterColumn'` bug

**Comment by rlaferla** [comment]
As for the pre-work bug, I have a question on how `transformToParquetjs() `is consumed/used.  It takes an array of `ParquetColumn` (i.e. `ParquetModel`) and transforms/converts it to a tuple of a `ParquetSchema` and an array of `BloomFilterColumn`.  The Bloom filter allows for a very fast test of non-existence in the data set.  The problem is that when a `ParquetColumn` does not have a bloom filter, it’s trying to create a `BloomFilterColumn` from null to add to the array but `BloomFilterColumn` is `{column:string}`

**Comment by rlaferla** [comment]
When deploying schemas, how should we handle specifying the model type and payload location?

**Comment by rlaferla** [comment]
> When deploying schemas, how should we handle specifying the model type and payload location?
> 
> e.g.
> 
> ```
> npm run deploy --modelType Parquet --payloadLocation OnChain --schema broadcast
> npm run deploy --modelType AvroBinary --payloadLocation IPFS --schema reply
> ```

It was decided that the Parquet schemas will always be IPFS and that the graphChange schema be AvroBinary/OnChain.
